"""
Reorder recommendation engine + PDF / Excel exports.
"""

from __future__ import annotations
import io
import pandas as pd
import numpy as np
from datetime import date
from data.catalog import get_sku


def priority_score(row: pd.Series) -> float:
    """
    Score 0-100 weighting:
      urgency (40)  : inverse days_until_stockout, capped
      margin  (20)  : margin per unit normalized
      volume  (20)  : reorder_qty normalized
      severity(20)  : critical=20, warning=12, watch=6, ok=0
    """
    urgency_raw = max(0, 30 - row.get("days_until_stockout", 30)) / 30.0
    urgency = urgency_raw * 40.0

    margin = min(1.0, float(row.get("unit_margin", 0)) / 5.0) * 20.0
    volume = min(1.0, float(row.get("reorder_qty", 0)) / 500.0) * 20.0
    sev = {"CRITICAL": 20, "WARNING": 12, "WATCH": 6, "OK": 0}.get(row.get("alert_level", "OK"), 0)
    return round(urgency + margin + volume + sev, 1)


def build_reorder_list(alerts: pd.DataFrame) -> pd.DataFrame:
    if alerts.empty:
        return alerts
    df = alerts[alerts["alert_level"].isin(["CRITICAL", "WARNING", "WATCH"])].copy()
    if df.empty:
        return df
    df["priority_score"] = df.apply(priority_score, axis=1)
    df = df.sort_values("priority_score", ascending=False).reset_index(drop=True)
    return df


def group_by_supplier(reorder_df: pd.DataFrame) -> pd.DataFrame:
    if reorder_df.empty:
        return reorder_df
    grp = reorder_df.groupby("supplier", as_index=False).agg(
        skus=("sku_id", "count"),
        total_units=("reorder_qty", "sum"),
        total_cost=("order_total_cost", "sum"),
        avg_priority=("priority_score", "mean"),
    ).sort_values("total_cost", ascending=False).reset_index(drop=True)
    return grp


# ---------------------------------------------------------------------------
# Excel export
# ---------------------------------------------------------------------------
def export_excel(reorder_df: pd.DataFrame) -> bytes:
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        reorder_df.to_excel(writer, sheet_name="Reorder", index=False)
        group_by_supplier(reorder_df).to_excel(writer, sheet_name="BySupplier", index=False)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# PDF export
# ---------------------------------------------------------------------------
def export_pdf(
    reorder_df: pd.DataFrame,
    company: str = "Warehouse Operations — Iyad Belkadi",
    lead_time: int = 3,
) -> bytes:
    """
    Build an A4-landscape PDF purchase order.

    Layout
    ------
    - Header     : "PURCHASE ORDER — <today>"
    - Company    : configurable subtitle
    - Table      : SKU | Product | Supplier | Zone | Qty | Unit price € |
                   Total € | Order by | Expected delivery
    - Total row  : bold, summing Qty and Total
    - Footer     : "Generated by Demand Forecasting Engine"
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        rightMargin=1*cm, leftMargin=1*cm, topMargin=1*cm, bottomMargin=1.4*cm,
        title="Purchase Order",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "title", parent=styles["Heading1"],
        fontSize=20, textColor=colors.HexColor("#1a1a2e"), spaceAfter=2,
    )
    company_style = ParagraphStyle(
        "company", parent=styles["Normal"],
        fontSize=11, textColor=colors.HexColor("#333333"), spaceAfter=8,
    )
    sub_style = ParagraphStyle(
        "sub", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#888888"),
    )
    footer_style = ParagraphStyle(
        "footer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#888888"), alignment=1,  # center
    )

    today_iso = date.today().isoformat()
    story = []
    story.append(Paragraph(f"PURCHASE ORDER — {today_iso}", title_style))
    story.append(Paragraph(company, company_style))

    if reorder_df.empty:
        story.append(Paragraph(
            "No SKUs in alert state. Inventory is healthy.",
            styles["Normal"],
        ))
    else:
        # Compute Expected delivery from Order by + lead_time
        df = reorder_df.copy()
        if "expected_delivery" not in df.columns:
            df["expected_delivery"] = df["order_by_date"].apply(
                lambda d: (pd.to_datetime(d) + pd.Timedelta(days=int(lead_time))).date().isoformat()
            )
        # Ensure unit_cost present
        if "unit_cost" not in df.columns:
            df["unit_cost"] = (df["order_total_cost"] / df["reorder_qty"].replace(0, 1)).round(2)

        total_qty   = int(df["reorder_qty"].sum())
        total_value = float(df["order_total_cost"].sum())
        critical    = int((df["alert_level"] == "CRITICAL").sum())

        story.append(Paragraph(
            f"<b>{len(df)}</b> SKUs &nbsp;|&nbsp; "
            f"<b>{critical}</b> critical &nbsp;|&nbsp; "
            f"Lead time: <b>{lead_time}</b> day(s) &nbsp;|&nbsp; "
            f"Total value: <b>€ {total_value:,.2f}</b>",
            sub_style,
        ))
        story.append(Spacer(1, 0.4*cm))

        head_labels = [
            "SKU", "Product", "Supplier", "Zone", "Qty",
            "Unit price €", "Total €", "Order by", "Expected delivery",
        ]
        data = [head_labels]
        for _, r in df.iterrows():
            data.append([
                str(r["sku_id"]),
                str(r["name"])[:34],
                str(r["supplier"])[:20],
                str(r["zone"]),
                f"{int(r['reorder_qty'])}",
                f"{float(r['unit_cost']):.2f}",
                f"{float(r['order_total_cost']):.2f}",
                str(r["order_by_date"]),
                str(r["expected_delivery"]),
            ])

        # Totals row
        data.append([
            "", "", "", "TOTAL",
            f"{total_qty}",
            "",
            f"{total_value:,.2f}",
            "", "",
        ])

        col_widths = [2.2*cm, 5.8*cm, 3.4*cm, 1.8*cm, 1.4*cm,
                      2.2*cm, 2.4*cm, 2.4*cm, 3.0*cm]
        t = Table(data, colWidths=col_widths, repeatRows=1)
        ts = TableStyle([
            # Header
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, 0), 9),
            ("ALIGN",      (4, 0), (6, 0), "RIGHT"),
            # Body
            ("FONTSIZE",   (0, 1), (-1, -2), 8),
            ("ALIGN",      (4, 1), (6, -2), "RIGHT"),
            ("ALIGN",      (7, 1), (8, -2), "CENTER"),
            ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("GRID",       (0, 0), (-1, -1), 0.25, colors.HexColor("#bbbbbb")),
            # Alternating rows (skip header [0] and total row [-1])
            ("ROWBACKGROUNDS", (0, 1), (-1, -2),
                [colors.white, colors.HexColor("#f3f3f5")]),
            # Total row — bold, contrasting band
            ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e7e7ee")),
            ("FONTNAME",   (0, -1), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE",   (0, -1), (-1, -1), 9),
            ("ALIGN",      (4, -1), (6, -1), "RIGHT"),
            ("LINEABOVE",  (0, -1), (-1, -1), 0.75, colors.HexColor("#1a1a2e")),
        ])
        t.setStyle(ts)
        story.append(t)

    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph(
        "Generated by Demand Forecasting Engine",
        footer_style,
    ))

    doc.build(story)
    return buf.getvalue()
