[theme]
base = "dark"
primaryColor = "#00C896"
backgroundColor = "#0b0b0b"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = false
headless = true

[runner]
fastReruns = true

[browser]
gatherUsageStats = false
